new: admin & org form
RocketChat/Rocket.Chat.Fuselage pull request #489
Opened 2021-07-05 15:49 UTC by dougfabris

- [x] I have read the Contributing Guide
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [ ] I have labeled the PR correctly with the related package
- [ ] I have run Loki's visual regression tests (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Proposed changes (including videos or screenshots)

## Issue(s)

## Further comments

2021-07-06 19:22 UTC, gabriellsh commented on packages/onboarding-ui/src/forms/helpers/Form/FormFooter.tsx
> +const FormContainer: FC = ({ children }): ReactElement => (
Component name does not match file name

2021-07-06 19:22 UTC, gabriellsh commented on packages/onboarding-ui/src/forms/helpers/Form/FormSubtitle.tsx
> +const FormTitle: FC = ({ children }): ReactElement => (
Does not match file name

2021-07-07 19:18 UTC, tassoevan requested changes
The `Form` component and its subcomponents would be better located under `common/`. I believe `forms/` should contain the implementations.

2021-07-12 04:10 UTC, tassoevan approved these changes

2021-07-12 04:10 UTC, merged