Onboarding UI PasswordLess login flow
RocketChat/Rocket.Chat.Fuselage pull request #565
Opened 2021-10-29 18:07 UTC by ujorgeleite

feat: add a login page with passwordless flow and default login page
feat: add a login page variation with the default behavior

A task that contains a description and Figma link for this screen.
https://app.clickup.com/t/1kc8qpc

This implementation will generate and interactive flow for login on rocket chat cloud systems.

2021-11-03 23:06 UTC, dougfabris requested changes

2021-11-03 23:06 UTC, dougfabris commented on packages/onboarding-ui/src/pages/LoginPage/LoginPage.tsx
> +              fontSize='p1'
Same related to `ActionLink`

2021-11-03 23:06 UTC, dougfabris commented on packages/onboarding-ui/src/pages/LoginPage/LoginPasswordLessForm.tsx
> +import { FieldGroup, Field, TextInput, Button } from '@rocket.chat/fuselage';
`form` files should be inside of `forms` folder and I'm missing the tests for them

2021-11-03 23:06 UTC, dougfabris commented on packages/onboarding-ui/src/pages/LoginPage/LoginPage.stories.tsx
> +import type { Story, Meta } from '@storybook/react';
I'm missing the story for the passwordless flow

2021-11-03 23:06 UTC, dougfabris commented on packages/onboarding-ui/src/pages/LoginPage/LoginPage.stories.tsx
> +_LoginPage.storyName = 'LoginPage';
```suggestion
_LoginPage.storyName = 'CloudDefaultLoginPage';
```

2021-11-03 23:06 UTC, dougfabris commented on packages/onboarding-ui/src/pages/LoginPage/LoginPage.tsx
> +type LoginPasswordLessProps = {
We could use more the power of the TS here, so much types...

2021-11-04 13:37 UTC, dougfabris commented on packages/onboarding-ui/src/pages/LoginPage/LoginPasswordLessForm.tsx
> +import { FieldGroup, Field, TextInput, Button } from '@rocket.chat/fuselage';
Additionally there's a bigger space between the fields and the button in the `form`!

2021-11-09 17:23 UTC, ujorgeleite commented on packages/onboarding-ui/.i18n/en.i18n.json
> +    "loginPage": {
Done!

2021-11-09 17:57 UTC, ujorgeleite commented on packages/onboarding-ui/src/pages/LoginPage/LoginDefaultForm.tsx
> +          <ActionLink fontWeight={400} fontSize='p1' onClick={onResetPassword}>
I remover the fontWeight but maintain the fontSize, because in fuselage documentation is a valid size.

2021-11-10 03:16 UTC, dougfabris approved these changes

2021-11-10 03:19 UTC, dougfabris approved these changes

2021-11-10 12:52 UTC, dougfabris approved these changes

2021-11-10 13:08 UTC, merged