feat: Fallback Component
RocketChat/Rocket.Chat.Fuselage pull request #572
Opened 2021-11-17 18:52 UTC by rique223

- [x] I have read the Contributing Guide
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [ ] I have labeled the PR correctly with the related package
- [ ] I have run Loki's visual regression tests (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Proposed changes (including videos or screenshots)

## Issue(s)

## Further comments

2021-11-17 18:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Fuselage?pullRequest=572) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Fuselage?pullRequest=572) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Fuselage?pullRequest=572) it.</sub>

2021-11-18 14:13 UTC, ujorgeleite requested changes

2021-11-18 14:13 UTC, ujorgeleite commented on packages/fuselage/src/components/Fallback/Fallback.stories.tsx
> +  //   component: Message,
Can we remove this unused and commented code?

2021-11-18 14:13 UTC, ujorgeleite commented on packages/fuselage/src/components/Fallback/Fallback.styles.scss
> +    max-width: 276px;
This fixed number can be replaced with a dynamic value or inherit sizes?

2021-11-18 14:13 UTC, ujorgeleite commented on packages/fuselage/src/components/Fallback/Fallback.tsx
> +  // variation?: 'danger';
I suggest to remove this unused code.

2021-11-30 18:07 UTC, dougfabris requested changes
I think we should remove the loki refs with the old component name

2021-11-30 18:13 UTC, dougfabris approved these changes

2021-11-30 20:42 UTC, dougfabris approved these changes

2021-11-30 21:19 UTC, merged